// Generated by https://quicktype.io

export interface UpdateAccountResponse {
  id: string;
  firstname: string;
  othername: string;
  lastname: string;
  current_class: string;
  gender: string;
  dob: string;
  spoken_languages: string[];
  telephone: string;
  nationality: string;
  address: string;
  index_no: number;
  last_school_attended: string;
  created_at: string;
  updated_at: string;
  photo_url: string;
  classes: string[];
}

export interface UpdateAccountPayload {
  password: string;
  old_password: string;
  passport_photo: string;
}
