// Generated by https://quicktype.io

export interface GetDashboardDataResponse {
  student: Student;
  classes: Class[];
  terms: GetDashboardDataResponseTerm[];
}

export interface Class {
  id: string;
  classname: string;
  shortname: string;
}

export interface Student {
  id: string;
  firstname: string;
  othername: string;
  lastname: string;
  current_class: Class;
  gender: string;
  dob: string;
  spoken_languages: string[];
  telephone: string;
  nationality: string;
  address: string;
  index_no: number;
  last_school_attended: string;
  created_at: string;
  updated_at: string;
  photo_url: string;
  username: number;
}

export interface GetDashboardDataResponseTerm {
  academic_year_id: string;
  academic_year: string;
  terms: Term[];
}

export interface Term {
  id: string;
  name: string;
  start_date: string;
  end_date: string;
  status: boolean;
}
